### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by ferreiro** [mikevercoelen/gulp-sass-glob#30]
Hello guys!,
I'm using your module into my gulp workflow like in the examples:

```
gulp.task('stylesheets', function () {
    return gulp
      .src('./client/web/public/dev/css/style.scss')
      .pipe(sassGlob())
      .pipe(sass())
      .pipe(gulp.dest('./client/web/public/production/css'))
})
```

In the style.scss, I have the following imports:

```
@import 'mixins/**/*.scss';
@import 'components/**/*.scss';
@import 'plugins/**/*.scss';
```

mixins, components and plugins are all in the folder inside the style.sccs like this:

```
.
├── components
│   ├── body.scss
├── mixins
│   ├── animations.scss
├── plugins
│   └── chat.scss
├── style.scss
```

So what is causing the errors? Because the files exist.

Thank you.
Jorge.

**Comment by StreamSurfer** [comment]
Same issue here.

**Comment by dsoldera** [comment]
Same problem here

**Comment by mcclaskiem** [comment]
Same issue as well

```
@import "partials/**/*.scss";
@import "atoms/**/*.scss";
@import "molecules/**/*.scss";
@import "organisms/**/*.scss";
@import "pages/**/*.scss";
```

The error message is informing me that organisms was misread even though molecules is the folder that does not have a valid scss file in it, only a .keep file we include from our boilerplate. The pages directory also only has a .keep file in it so technically with molecules commented out this should still fail.

Could this be something to do with the index of the files in the error messages?

**Comment by DanielaValero** [comment]
Hello,

What version do you guys have?
Is there any log that you could share?

**Comment by mcclaskiem** [comment]
Im on 1.0.6 currently, installed via NPM.

**Comment by mkg0** [comment]
it seems 1.0.5 is last stable version. all of 6,7,8 minor versions are still crashing.

**Comment by Jazcash** [comment]
I'm getting this error consistently when saving a file but not making any modifications. E.g., adding a space, deleting it and resaving a file. If an actual difference is made then it works fine.

**Comment by tomgrooffer** [comment]
Guys I can't reproduce this error, I checked all 6, 7 and 8 versions and they seem to work fine at me.

Please share me your gulpfile.

@Jazcash Are you getting those errors when using live reload?

**Comment by Jazcash** [comment]
My bad, I found that VSCode was the issue.

**Comment by mcclaskiem** [comment]
@Jazcash Can you provide some more insight, I am using VSCode as well.

**Comment by Jazcash** [comment]
Similar issue to this I think: https://github.com/dlmanning/gulp-sass/issues/534
https://github.com/olefredrik/FoundationPress/issues/731

Don't worry, pretty sure gulp-sass-glob isn't the issue.

**Comment by nategreen** [comment]
Had the same issue, not using VS Code, and downgrading from ^1.0.8 to 1.0.5 fixed it for me.

**Comment by nategreen** [comment]
Never mind...re-upgraded and it was still fine. While it was working, I corrected a couple of errors in my Sass...things like missing variables or placeholders. Could that possibly have been the/an issue? It seems like this package shouldn't care about that.

**Comment by Sam-Pryor** [comment]
For anyone using Sublime Text getting this same issue:
In Preferences.sublime-settings, in your user settings add:
"atomic_save": true
