### ISSUE TITLE
Globbing Time causes error

### ISSUE THREAD

**Issue by scottsawyer** [mikevercoelen/gulp-sass-glob#42]
I have gulpfile.js with a sass task like so:
```
gulp.task('sass', function() {
  return gulp.src('scss/style.scss')
    .pipe(sassGlob())
    .pipe(debug({title: 'glob'}))
    .pipe($.sass()
      .on('error', $.sass.logError))
    .pipe($.autoprefixer({
      browsers: ['last 2 versions', 'ie >= 9']
    }))
    .pipe(debug({title: 'unicorn'}))
    .pipe(gulp.dest('css'));
});
```

Sometimes, I think it only happens when saving a new partial, it seems to take too long to glob, and when the sass is run, the files is still being written.

```
[18:11:28] Starting 'sass'...
[18:11:28] glob scss/style.scss
[18:11:28] glob 1 item

Error in plugin 'sass'
Message:
    scss/style.scss
Error: File to import not found or unreadable: utils/**/*.
       Parent style sheet: /var/www/html/web/themes/custom/truefit/scss/style.scss
        on line 1 of scss/style.scss
>> @import "utils/**/*";
[18:11:28] unicorn 0 items
[18:11:28] Finished 'sass' after 13 ms
```

When I re-save the partial, there is no error.  
```
[18:12:09] Starting 'sass'...
[18:12:09] glob scss/style.scss
[18:12:09] glob 1 item
[18:12:09] unicorn scss/style.css
[18:12:09] unicorn 1 item
[18:12:09] Finished 'sass' after 7.64 ms
```

I am not sure if the first one takes 13ms because it's catching / writing the error, or if because it takes longer to glob a new file.

Thoughts?

**Comment by scottsawyer** [comment]
Mike, will you tell me why you are closing the issue with no comment?

**Comment by mikevercoelen** [comment]
Should be fixed in new release, please test and let me know.

**Comment by scottsawyer** [comment]
Thanks Mike, I will test and let you know.  It will be a few days before I can test.

**Comment by tsmuse** [comment]
Any resolution on this? I'm running into this same error when using it in a watch function. It seems to run successfully once, and then when the watcher runs gulp-sass throws error listed above because it can't figure out what the glob path is, then when it runs again it appears to run successfully but it doesn't actually build anything.

**Comment by scottsawyer** [comment]
I wound up using gulp-wait, adding 600ms delay between glob and sass

**Comment by tsmuse** [comment]
Cool, I'll give that a shot. Thanks :)
