### ISSUE TITLE
Nested Globbing - Working

### ISSUE THREAD

**Issue by Goon3r** [mikevercoelen/gulp-sass-glob#43]
Hello,

Just a quick one to inform you that nested globbing appears to be working if you combine this package with another (node-sass-globbing)

Below is a simplified untested version of my approach but it should work all the same.

```
var gulp = require('gulp'),
    nodeSassGlobbing = require('node-sass-globbing'),
    sass = require('gulp-sass'),
    sassGlob = require('gulp-sass-glob');

gulp.src('some/scssfile.scss')
    .pipe(sassGlob())
    .pipe(sass({
        importer: nodeSassGlobbing
    }))
    .pipe(gulp.dest('build'))
```

It may be worth carrying out some tests on this and adding a note to this packages README.

Hope it helps some out!

**Comment by mikevercoelen** [comment]
@Goon3r Thanks so much man, I will add this and add it to the README in a release soon ;)

**Comment by donquixote** [comment]
Would be interesting to know the other plugin does the entire job by itself, or you need both.
